### ISSUE TITLE
simple2.csv

### ISSUE THREAD

**Issue by j450h1** [mkierans/Telstra#2]
Hi Matt,

I'm trying to run the code (Xgboost with hyperopt tuning.py), but I can't find the file simple2.csv. Can you upload it?

Thanks,

Jas

**Comment by mkierans** [comment]
Hey Jas,

Unfortunately I'm having problems uploading that file to github (says it is
too large). I've added some python code that should produce the file for
you though (you will need to download the data files into the same folder
for it to run properly).

Let me know if that works for you.

Cheers,
Matt

**Comment by j450h1** [comment]
Thanks for doing that Matt. Yes, I was able to successfully generate the sample.csv file and then run the hyperopt script successfully.
